### ISSUE TITLE
Could you help upgrade the vulnerble dependency in color-detection-jdla

### ISSUE THREAD

**Issue by JoeGardner000** [JosueDLA/ColorDetection#1]
Hi, @JosueDLA , I'd like to report a vulnerability issue in **color-detection-jdla_0.0.2**.
### Issue Description
I noticed that **color-detection-jdla_0.0.2** directly depends on **opencv-python_4.5.4.60**.
However, **opencv-python_4.5.4.60** sufferes from the vulnerabilites which the C libraries exposed as following dependency graph shows. Refer to [issue](https://github.com/opencv/opencv-python/issues/646).

### Dependency Graph between Python and Shared Libraries
![image (4)](https://user-images.githubusercontent.com/103017573/161753038-260f480a-47eb-4c8b-9477-3afb0ca23ef8.png)
### Suggested Vulnerability Patch Versions
**opencv-python** has upgraded these vulnerable C libraries to patch versions in release ***4.5.5.64***. 

Python build tools cannot report vulnerable C libraries, which may induce potential security issues to many downstream Python projects.
Could you please upgrade this vulnerable dependency?

Thanks for your help~
Best regards,
JoeGardner

**Comment by JosueDLA** [comment]
Hi @JoeGardner000 thanks for opening an issue, the dependencies have been updated in c334be70394ee1a698755e2bceedfc6a77f7f423.

Best regards
Josué de León
